# Generated by Django 2.1 on 2018-08-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_comments', models.CharField(max_length=500)),
                ('exit_comments', models.CharField(max_length=500)),
            ],
        ),
    ]
