# Generated by Django 2.1 on 2018-09-10 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('position', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=100)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('entry_date', models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 10, 6, 5, 31, 557507))),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 9, 10, 6, 5, 31, 557507))),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entry_comments', models.CharField(max_length=500)),
                ('exit_comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
