# Generated by Django 2.1 on 2018-08-27 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20180827_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='position',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=100),
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 27, 19, 14, 30, 828153)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='exit_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=datetime.datetime(2018, 8, 27, 19, 14, 30, 828153)),
        ),
    ]
