# Generated by Django 2.1 on 2018-09-11 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20180911_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='user',
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 11, 5, 59, 19, 102303)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 9, 11, 5, 59, 19, 102303)),
        ),
    ]
