# Generated by Django 2.1 on 2018-10-06 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0033_auto_20181006_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='account_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 6, 9, 34, 58, 382584)),
        ),
        migrations.AlterField(
            model_name='trades',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2018, 10, 6, 9, 34, 58, 382584)),
        ),
    ]
