# Generated by Django 2.1 on 2018-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starting_balance',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
