# Generated by Django 2.1 on 2018-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181001_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
