# Generated by Django 2.1 on 2018-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181002_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='C:\\Users\\Jacob\\Documents\\python\\django\\tradetracker\\media'),
        ),
    ]
