# Generated by Django 2.1 on 2018-10-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181003_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
