# Generated by Django 2.1 on 2018-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20181006_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.FloatField(blank=True),
        ),
    ]
